Feat/add e2e for chat
voorhoede/lean-web-kit pull request #107
Opened 2018-09-12 09:29 UTC by Jamerrone

- [Trello](https://trello.com/c/38f377MQ/108-5-add-e2e-for-chat)

2018-09-12 09:53 UTC, jbmoelker requested changes
Please also add new tests for or add to existing tests:
* focus is on "agree" button when opt-in is opened
* opt-in disappears on "decline"
* focus is on chat button after "decline"

2018-09-12 09:53 UTC, jbmoelker commented on src/client/components/lazy-chat/lazy-chat.vue
> +      v-test:lazyChatButtonIdentity
The reason we had "Identity" in the selector name is that the element around the logo was simply called "brand identity". You don't have to use it in every test directive. So simply `lazyChatButton` etc.

2018-09-12 09:53 UTC, jbmoelker commented on test/cypress/integration/lazy-chat.test.js
> +import { crispWebsiteId } from '../../../src/client/static/data/app.json'
can you use a variable here so other developers know what the outcome means?
```js
const chatIsEnabled = !!crispWebsiteId
```

2018-09-12 09:53 UTC, jbmoelker commented on test/cypress/integration/lazy-chat.test.js
> +  it('is only present if Crisp ID is set', () => {
Use a variable so other devs directly see both the if and the else apply to the same element
```js
const button = cy.get(lazyChatButton)
if (chatIsEnabled) {
  button.should('be.visible')
} else {
  button.should('not.exist')
}
```

2018-09-12 09:53 UTC, jbmoelker commented on test/cypress/integration/lazy-chat.test.js
> +
I think you need to make all of the tests after this point conditional. They only apply if the chat is enabled, so:
```js
if (!chatIsEnabled) {
  return
}
```

2018-09-12 09:53 UTC, jbmoelker commented on test/cypress/integration/lazy-chat.test.js
> +    cy.clearLocalStorage()
I think Cypress allows you to be more specific, so you don't affect other tests:
```js
cy.clearLocalStorage('terms_conditions')
```

2018-09-12 09:53 UTC, jbmoelker commented on test/cypress/integration/lazy-chat.test.js
> +  it('asked me to accept the T&C when I hit the chat button ("terms_conditions" === false)', () => {
Try to only use human language here, so something like:
"when I haven't accepted T&C yet, I'm prompted to accept the T&C when I hit the chat button"

(same for the following test)

2018-09-12 09:53 UTC, jbmoelker commented on test/cypress/integration/lazy-chat.test.js
> +const lazyChatButtonIdentity = '[data-test="lazyChatButtonIdentity"]'
everything here is scoped to this file and we're already in the `lazy-chat` directory, so you can simplify your variable names to be more readable (`chatButton`, `optInDialog` (or whatever it is))

2018-09-12 09:53 UTC, jbmoelker commented on test/cypress/integration/lazy-chat.test.js
> +      .children('button.button--primary')
add a `v-test` to the button you want to address here (same for following test)

2018-09-12 09:53 UTC, jbmoelker commented on test/cypress/integration/lazy-chat.test.js
> +  it('is only present if T&C is accepted', () => {
`it('Crisp client is only ...`

2018-09-12 09:53 UTC, jbmoelker commented on test/cypress/integration/lazy-chat.test.js
> +  it('setted the focus correctly', () => {
`it('sets the focus on the message input when opening the Crisp client'`

2018-09-14 11:12 UTC, vbvnvmfjg approved these changes

2018-09-14 12:01 UTC, jbmoelker approved these changes

2018-09-14 12:02 UTC, merged