feat: added <feature-list />
voorhoede/lean-web-kit pull request #110
Opened 2018-09-17 13:51 UTC by anandgraves

2018-10-01 09:22 UTC, jbmoelker submitted a review, later dismissed
Nice work! Just a bit of BEM naming and a question :)

2018-10-01 09:22 UTC, jbmoelker commented on src/client/components/feature-list/feature-list.vue
> +      <div class="feature-item">
Still part of the same (single file) component, so still the same prefix `feature-list`.
So I'd either do:
```
.feature-list__item
  .feature-list__item-content
  .feature-list__item-title
  .feature-list__item-image
  .feature-list__item-body
```
or

```
.feature-list__item
  .feature-list__item__content
  .feature-list__item__title
  .feature-list__item__image
  .feature-list__item__body
```

2018-10-01 09:22 UTC, jbmoelker commented on src/client/components/feature-list/feature-list.vue
> +@media (min-width: 600px) {
Should we also add two in a row when possible? One in a row does create a very long page.

2019-02-11 09:18 UTC, Remcoman requested changes

2019-02-11 09:18 UTC, Remcoman commented on src/client/components/feature-list/feature-list.vue
> +      require: true,
small typo here :-)

2019-02-11 10:41 UTC, vbvnvmfjg commented on src/client/components/feature-list/feature-list.vue
> +      require: true,
I fixed the typo

2019-02-11 11:30 UTC, Remcoman submitted a review, later dismissed

2019-02-11 15:21 UTC, merged