Feat/enhanced social share
voorhoede/lean-web-kit pull request #51
Opened 2018-07-18 12:53 UTC by brunadafonseca

Resolves Trello issue #48: [Enhanced social share](https://trello.com/c/qlCnGILS/48-3-enhanced-social-share)

2018-07-18 21:11 UTC, jbmoelker commented on src/client/components/social-share/social-share.vue
> +         <span class="a11y-sr-only">{{ $t('share_on_twitter') }}</span>
How about `$t('share_on_platform', { platform: 'Twitter' })`? In the CMS we can then set a single translation: "Share on {platform}".

2018-07-18 21:12 UTC, jbmoelker commented on src/client/components/social-share/social-share.vue
> +import TwitterLogo from '../../static/images/twitter-logo.svg'
Missed one?

2018-07-18 21:13 UTC, jbmoelker commented on dato.config.js
> +  const { title, hasToc, sharingButton } = page
How about `hasShareButton`? I know I keep changing my mind, sorry.

2018-07-19 07:26 UTC, brunadafonseca commented on src/client/components/social-share/social-share.vue
> +         <span class="a11y-sr-only">{{ $t('share_on_twitter') }}</span>
Much better! 😄

2018-07-19 10:41 UTC, jurgenbelien requested changes
Be mindful of your class names, use BEM!

2018-07-19 10:41 UTC, jurgenbelien commented on src/client/components/social-share/social-share.vue
>  .visible {
use a BEM selector for visible: `.social-share__link--visible`. Otherwise this specific styling will be applied anywhere the class `visible` is used.

2018-07-19 10:41 UTC, jurgenbelien commented on src/client/components/social-share/social-share.vue
> +      <a :href="`https://twitter.com/intent/tweet?text=${title} ${encodedDescription} ${encodedUrl}`"
For the next time, consider writing this in v-for loop.

2018-07-19 13:36 UTC, jurgenbelien approved these changes

2018-07-19 13:36 UTC, merged