Track chat lifecycle events
voorhoede/lean-web-kit pull request #76
Opened 2018-08-08 13:27 UTC by brunadafonseca

2018-08-09 09:21 UTC, phortuin reviewed
Is it possible to make the `track` method a separate component? So refactor `opt-in.vue` and `lazy-chat.vue` to have access to a plugin or module that handles ga events?

2018-08-10 09:40 UTC, jbmoelker requested changes

2018-08-10 09:40 UTC, jbmoelker commented on src/client/components/opt-in/opt-in.vue
> +    track (label) {
`label` -> `eventLabel`?

2018-08-10 09:40 UTC, jbmoelker commented on src/client/components/lazy-chat/lazy-chat.vue
>      <button v-if="chatButtonIsShown"
`type="button"`

2018-08-10 09:40 UTC, jbmoelker commented on src/client/components/lazy-chat/providers/crisp.js
> +function onOpened () {
I'd rather keep the `ga` implementation out of the `crisp` provider. So can do to the same here as you do `onSessionLoaded` in the chat icon feature? Expose `onOpened` and `onClosed` as methods on this provider and make them accept a callback. In `lazy-chat` you can then use these methods and do the tracking.

2018-08-10 09:40 UTC, jbmoelker commented on src/client/components/lazy-chat/lazy-chat.vue
> +    track () {
To be consistent I'd set the `eventAction` to `click` and the `eventLabel` to `start`?
And actually, I'd change the signature of this method to `track(eventLabel)` like you do in `opt-in`. That way you can use it in `handleClick` and also `onOpened` and `onClosed` as suggested in my comment in `providers/crisp.js`

2018-08-10 13:15 UTC, jbmoelker approved these changes

2018-08-10 13:15 UTC, merged