Feat/download files
voorhoede/lean-web-kit pull request #84
Opened 2018-08-16 13:34 UTC by anandgraves

2018-08-16 14:03 UTC, jbmoelker requested changes
Looks nice in the browser! Please use the `/en/test/` page rather than the homepage for testing components. Eventually we want people to visit the homepage and not run into weird components.

2018-08-16 14:03 UTC, jbmoelker commented on src/client/components/download-files/download-files.vue
> +.download-files__link:hover::after {
Also `:focus`? and do you need to repeat the `content: '↓';`?

2018-08-16 14:03 UTC, jbmoelker commented on src/client/components/download-files/download-files.vue
> +        :download="`${item.slug}.${item.file.format}`"
How about using `item.title` as it's more user friendly I think:
```vue
<a :download="`${item.title}.${item.file.format}`"
```

2018-08-16 14:03 UTC, jbmoelker commented on src/client/components/download-files/download-files.vue
> +      class="download-files__item">
Unused class?

2018-08-16 14:03 UTC, jbmoelker commented on src/client/components/download-files/download-files.vue
> +      validator: function(data) {
I think this can be written more expressive, and should apply to all files, not just the first. So:
```js
validator: function(files) {
  const requiredProps = ['title', 'file', 'slug', 'id']
  return files.every(file => requiredProps.every(prop => file.hasOwnProperty(prop))
},
```
I'm cheating on the `file.format` and `file.url` but I assume they're there if `file` is set. But otherwise, feel free to make more specific.

2018-08-16 14:03 UTC, jbmoelker commented on src/client/components/download-files/download-files.stories.js
> +import { withKnobs, text } from '@storybook/addon-knobs'
unused?

2018-08-16 14:03 UTC, jbmoelker commented on src/client/components/download-files/download-files.stories.js
> +          "id": "364027",
You're not using the id.

2018-08-16 14:03 UTC, jbmoelker commented on src/client/components/download-files/download-files.stories.js
> +            "url": "https://www.datocms-assets.com/6068/1534418780-josefin-sans-300.woff2"
I'd like stories to be standalone and not dependent on the CMS. If these files are removed from the CMS, the story no longer works. So use something else please. Maybe a tiny blob URL?

2018-08-16 14:03 UTC, jbmoelker commented on src/client/components/download-files/download-files.stories.js
> +          "title": "Josefin Sans 300"
I'd like the titles to be different and different lengths so that you can see what the component looks like when the download icons are not aligned.

2018-08-16 14:03 UTC, jbmoelker commented on src/client/components/download-files/download-files.vue
> +.download-files__link::after {
Should we move this to `::before` so that the download icons are always vertically aligned?

2018-08-16 14:12 UTC, anandgraves commented on src/client/components/download-files/download-files.vue
> +.download-files__link:hover::after {
No, good one. `content` doesn't need to be repeated.

2018-08-16 14:14 UTC, anandgraves commented on src/client/components/download-files/download-files.stories.js
> +            "url": "https://www.datocms-assets.com/6068/1534418780-josefin-sans-300.woff2"
Yes, didn't think of that. Good idea, will use a data uri.

2018-08-17 08:30 UTC, jbmoelker approved these changes

2018-08-17 08:35 UTC, merged