Feat/404
voorhoede/lean-web-kit pull request #97
Opened 2018-09-04 12:11 UTC by anandgraves

2018-09-04 15:28 UTC, jbmoelker requested changes

2018-09-04 15:28 UTC, jbmoelker commented on src/client/layouts/error.vue
> +  <div>
`<div>` not needed

2018-09-04 15:28 UTC, jbmoelker commented on src/client/layouts/error.vue
> +  import notfoundI18n from '../static/data/404.json'
`notfoundI18n` -> `pageI18n`

2018-09-04 15:28 UTC, jbmoelker commented on src/client/layouts/error.vue
> +      notfound() { return notfoundI18n[this.locale] },
`notfound` -> `page`

2018-09-04 15:28 UTC, jbmoelker commented on dato.config.js
> +  const redirectToLocalized404s = locales.map(locale => `/${locale}/* /${locale}/404/ 404`).join('\n')
```js
const redirectToDefaultLocale = `/ /${defaultLocale}/ 301`
const redirectRulesFromCms = redirects
    .map(redirect => `${redirect.from} ${redirect.to} ${redirect.statusCode}`)
const redirectRules404s = locales.map(locale => `/${locale}/* /${locale}/404/ 404`)

return [redirectToDefaultLocale, ...redirectRulesFromCms, ...redirectRules404s].join("\n")
```

2018-09-04 15:28 UTC, jbmoelker commented on src/client/layouts/error.vue
> +  export default {
set `title` in `meta` to `page.title`: https://github.com/nuxt/nuxt.js/blob/master/lib/app/components/nuxt-error.vue#L27

2018-09-06 14:44 UTC, Jamerrone approved these changes

2018-09-07 08:00 UTC, jbmoelker approved these changes

2018-09-07 08:00 UTC, merged